# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2ea061325ae111b02ed37a89dd5a8cb8350bd808f926aac26141ce4bc0dabaac4ef75ca4f8c5bab42e5e9437ea3fb5148b5fbc5ea0abeb19cfd80b35356232d

test:
  secret_key_base: 6476690effe73e9e61b955783bee56dabf93541d9e0fa565839b25ca68b8adafc75a202ecd68d33e486ab6279e9c211ced8898c05b75dbf1c3225cbc11fbcd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
